sudo: required
dist: trusty
language: python
python:
  - "3.5"
services:
  - docker
script:
  - pip install codecov && docker volume create --name=webmonitor && docker-compose up -d && docker-compose exec web /bin/sh -c "python3 -m coverage run manage.py test && python3 -m coverage xml && mv coverage.xml shared" && cd shared && python3 -m codecov
