# Generated by Django 2.2.6 on 2019-10-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Server'),
        ),
    ]
