# Generated by Django 2.2.6 on 2019-10-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_record_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'settings'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
