# Generated by Django 2.2.6 on 2019-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20191031_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcher',
            name='method_arg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
