# Generated by Django 2.2.6 on 2019-11-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('monitor', '0006_watcher_method_arg'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='platform',
            field=models.CharField(blank=True, choices=[('ml', 'email')], max_length=255, null=True),
        ),
    ]
