# Generated by Django 2.2.6 on 2019-11-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20191101_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcher',
            name='trigger',
            field=models.BooleanField(default=False),
        ),
    ]
